In [7]:
import  pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
# x=np.array([1,2,3,4,5])
# y=np.array([2,4,5,4,5])
# # print(x,y)

In [19]:
mean_x=np.mean(x)
mean_y=np.mean(y)

print(f"menas of x is :{mean_x}")
print(f"menas of y is :{mean_y}")

menas of x is :3.0
menas of y is :4.0


In [27]:
num=np.sum((x-mean_x)*(y-mean_y))
num
deno=np.sum((x-mean_x)**2)
deno

10.0

In [29]:
slope=num/deno
print(slope)

0.6


In [31]:
intercept=mean_y-slope*mean_x
intercept

2.2

In [33]:
manual_pread=slope*x+intercept
manual_pread

array([2.8, 3.4, 4. , 4.6, 5.2])

In [50]:
9x_reshaped=x.reshape(-1,1)
x_reshaped

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [34]:
model=LinearRegression()

In [51]:
x_reshaped.shape

(5, 1)

In [54]:
y=y.reshape(1,-1)
y
# y.shape

array([[2, 4, 5, 4, 5]])

In [12]:
x=np.array([[1],[2],[3],[4],[5]])
y=np.array([0,0,0,1,1])

In [13]:
model=LogisticRegression()
model.fit(x,y)

LogisticRegression()

In [34]:
 x_test=np.linspace(0,6,10).reshape(-1,1) # it create line interval bw line to gether data 
prob=model.predict_proba(x_test)
 # print(prob)


In [32]:
y_pred=model.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [35]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(x,y,color="red")
plt.scatter(x_test,y,color="red")
plt.scatter(x_test,prob[:0],cpolr