In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler,Normalizer,MinMaxScaler

In [2]:
df=pd.read_csv("data.csv").dropna()

In [5]:
print(df)
x=df[["Age","Salary"]].values.astype(np.float64)
df.describe()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


,Age,Salary
count,8.000000,8.000000
mean,38.625000,65250.000000
std,8.210403,12232.859729
min,27.000000,48000.000000
25%,33.750000,57000.000000
50%,37.500000,64000.000000
75%,45.000000,73750.000000
max,50.000000,83000.000000


In [11]:
standar_scaler=StandardScaler()
print("Standardization")
print(standar_scaler.fit_transform(x))

Standardization
[[ 0.69985807  0.58989097]
 [-1.51364653 -1.50749915]
 [-1.12302807 -0.98315162]
 [-0.08137885 -0.37141284]
 [-0.47199731 -0.6335866 ]
 [ 1.22068269  1.20162976]
 [ 1.48109499  1.55119478]
 [-0.211585    0.1529347 ]]


In [13]:
Normal_scaler=Normalizer()
print("Normalizer")
print(Normal_scaler.fit_transform(x))

Normalizer
[[6.11110997e-04 9.99999813e-01]
 [5.62499911e-04 9.99999842e-01]
 [5.55555470e-04 9.99999846e-01]
 [6.22950699e-04 9.99999806e-01]
 [6.03448166e-04 9.99999818e-01]
 [6.07594825e-04 9.99999815e-01]
 [6.02409529e-04 9.99999819e-01]
 [5.52238722e-04 9.99999848e-01]]


In [14]:
MinMax=MinMaxScaler()
print("MinMaxScaler")
print(MinMax.fit_transform(x))

MinMaxScaler
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.34782609 0.28571429]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]
